"""Grasp taxonomy, proportional myoelectric control, and a simulated force feedback loop."""

from hand_controller.algorithm import (
    BandPassSlipDetector,
    CoContractionConfig,
    ForceConfig,
    MyoelectricController,
    ProportionalConfig,
    ProportionalForceRegulator,
    SlipDetectorConfig,
    SlipResponseConfig,
    command_latency,
    control_law,
    mode_switch_latency,
)
from hand_controller.analysis import (
    GraspMetrics,
    format_evaluation,
    format_taxonomy,
    format_trial,
    success_rate,
    summarise,
    summarise_set,
)
from hand_controller.model import (
    GRASP_TAXONOMY,
    OBJECT_SET,
    GraspDefinition,
    GraspObject,
    HandConfiguration,
    default_hand,
    equilibrium_force,
    grasp,
    grasp_object,
    opposition_span,
)
from hand_controller.pipeline import (
    EVALUATION_SET,
    GraspTrace,
    TrialConfig,
    reference_trial,
    run_evaluation,
    simulate,
)

__all__ = [
    "EVALUATION_SET",
    "GRASP_TAXONOMY",
    "OBJECT_SET",
    "BandPassSlipDetector",
    "CoContractionConfig",
    "ForceConfig",
    "GraspDefinition",
    "GraspMetrics",
    "GraspObject",
    "GraspTrace",
    "HandConfiguration",
    "MyoelectricController",
    "ProportionalConfig",
    "ProportionalForceRegulator",
    "SlipDetectorConfig",
    "SlipResponseConfig",
    "TrialConfig",
    "__version__",
    "command_latency",
    "control_law",
    "default_hand",
    "equilibrium_force",
    "format_evaluation",
    "format_taxonomy",
    "format_trial",
    "grasp",
    "grasp_object",
    "mode_switch_latency",
    "opposition_span",
    "reference_trial",
    "run_evaluation",
    "simulate",
    "success_rate",
    "summarise",
    "summarise_set",
]

__version__ = "0.1.0"
